export const FETCH_RESOURCE = 'FETCH_RESOURCE';
export const FETCH_RESOURCE_SUCCESS = 'FETCH_RESOURCE_SUCCESS';
export const FETCH_RESOURCE_ERROR = 'FETCH_RESOURCE_ERROR';

export const SET_STARSHIPS_LIST = 'SET_STARSHIPS_LIST';
export const SET_STARSHIPS_ITEM = 'SET_STARSHIPS_ITEM';
